### PR TITLE
Update issue.js

### PR DESCRIPTION
**Pull request by neoatomic**
Needs reviewing to make sure it doesn't break the bot.
@miigotu

### CODE REVIEW

**Comment by SickRage2** [comment]
Thanks for the pull request! Before a real human comes by, please make sure your PR has all of the below criteria checked
- [x] Give a description on what the PR is for.
- [ ] Make sure your PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review

Please make sure you also read [contribution guide](https://github.com/SickRage/SickRage/blob/master/contributing.md) and followed all of the steps.

Thanks!

**Comment by miigotu** [comment]
Thats too much text, add a link to that info on a wiki page if we really need it =P

**Comment by neoatomic** [comment]
The thing is they wont read it. :( Let me see if i can clean it up a little.

**Comment by miigotu** [comment]
Its just supposed to be a short and sweet greeting, not a troubleshooting guide lol

**Comment by neoatomic** [comment]
I like users that help themselves. :P

**Pull request closed without merging**
